### ISSUE TITLE
Fatal error: Uncaught exception 'Less_Exception_Chunk' with message 'ParseError: missing closing `*/`

### ISSUE THREAD

**Issue by bossev** [oyejorge/less.php#291]
After updating wp-less to 1.8.0 I have this error when I activate the wp plugin.
```
Fatal error: Uncaught exception 'Less_Exception_Chunk' with message 'ParseError: missing closing `*/` in layout.less on line 371, column 3 369| } 370| 371| } /* /media query  372| ' in /home/www/website/wp-content/plugins/wp-less/vendor/oyejorge/less.php/lib/Less/Parser.php:535 Stack trace: #0 /home/www/website/wp-content/plugins/wp-less/vendor/oyejorge/less.php/lib/Less/Parser.php(343): Less_Parser->GetRules('/home/www/79ide...') #1 /home/www/website/wp-content/plugins/wp-less/vendor/oyejorge/less.php/lib/Less/Tree/Import.php(277): Less_Parser->parseFile('/home/www/79ide...', '', true) #2 /home/www/website/wp-content/plugins/wp-less/vendor/oyejorge/less.php/lib/Less/Tree/Import.php(193): Less_Tree_Import->ParseImport('/home/www/79ide...', '', Object(Less_Environment)) #3 /home/www/website/wp-content/plugins/wp-less/vendor/oyejorge/less.php/lib/Less/Tree/Ruleset.php(248): Less_Tree_Import->compile(Object(Less_Environment)) #4 /home/www/website/wp-content/plugins/wp-less/vendor/oyejorge/less.p in /home/www/website/wp-content/plugins/wp-less/vendor/oyejorge/less.php/lib/Less/Parser.php on line 535
```
Any ideas what can I do?

**Comment by bossev** [comment]
it was caused by the WP theme. The author of the theme patched their code and the issue was fixed.
