### ISSUE TITLE
PHP 7.x compatiblity

### ISSUE THREAD

**Issue by derchrisuk** [oyejorge/less.php#369]
Hi,

is 1.7.0.9/10 compatible with recent PHP 7.1/7.2 versions?
We are currently using the 1.7.0.9 version, and when using with PHP 7.1/7.2, a few less files will fail to compile with the following:

```
ErrorException: count(): Parameter must be an array or an object that implements Countable in lib/less.php/Less.php:9320
Stack trace:
#0 lib/less.php/Less.php(9320): exception_error_handler(2, 'count(): Parame...', 'lib/les...', 9320, Array)
#1 lib/less.php/Less.php(4390): Less_Visitor_toCSS->visitRuleset(Object(Less_Tree_Ruleset), false)
#2 lib/less.php/Less.php(9326): Less_VisitorReplacing->visitObj(Object(Less_Tree_Ruleset))
#3 lib/less.php/Less.php(4390): Less_Visitor_toCSS->visitRuleset(Object(Less_Tree_Ruleset), false)
#4 lib/less.php/Less.php(9326): Less_VisitorReplacing->visitObj(Object(Less_Tree_Ruleset))
#5 lib/less.php/Less.php(4390): Less_Visitor_toCSS->visitRuleset(Object(Less_Tree_Ruleset), false)
#6 lib/less.php/Less.php(4414): Less_VisitorReplacing->visitObj(Object(Less_Tree_Ruleset))
#7 lib/less.php/Less.php(6814): Less_VisitorReplacing->visitArray(Array)
#8 lib/less.php/Less.php(9370): Less_Tree_Ruleset->accept(Object(Less_Visitor_toCSS))
#9 lib/less.php/Less.php(9312): Less_Visitor_toCSS->visitRulesetRoot(Object(Less_Tree_Ruleset))
#10 lib/less.php/Less.php(4390): Less_Visitor_toCSS->visitRuleset(Object(Less_Tree_Ruleset), false)
#11 lib/less.php/Less.php(9228): Less_VisitorReplacing->visitObj(Object(Less_Tree_Ruleset))
#12 lib/less.php/Less.php(286): Less_Visitor_toCSS->run(Object(Less_Tree_Ruleset))
#13 lib/less.php/Less.php(200): Less_Parser->PostVisitors(Object(Less_Tree_Ruleset))
#14 lib/less.php/Cache.php(170): Less_Parser->getCss()
#15 lib/less.php/Cache.php(106): Less_Cache::Cache(Array, Array)
#16 lib/helper.php(70): Less_Cache::Get(Array, Array)
#17 index.php(211): handle_lesscss_request('configs/confere...', '../../configs/c...')
#18 {main}
```

Running the same with 7.0 works fine.

Thanks,
derchris

**Comment by playmono** [comment]
As far as I debug this application it is NOT compatible.

Maybe using nightly version? I found it resolves some PHP7 issues.

https://github.com/oyejorge/less.php/commit/669acc51817a8da162b5f1b7137e79f0e4acc636#diff-56cf4fc3cb1ede7b9ea0952085171a02
